# Generated by Django 6.1.1 on 2026-09-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
