# Generated by Django 6.1.1 on 2026-09-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_portfolio_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Stock Trader', max_length=100)),
                ('contact_email', models.EmailField(default='support@stocktrader.com', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default='We are currently under maintenance. Please check back later.')),
                ('starting_wallet_balance', models.DecimalField(decimal_places=2, default=100000.0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
