# Generated by Django 6.1.1 on 2026-09-15 03:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='stop_loss_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='daily_loss_limit',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_reset_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='max_position_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='wallet',
            name='todays_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
