# Generated by Django 6.1.1 on 2026-09-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_portfolio_stop_loss_price_portfolio_target_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='highest_pnl_since_entry',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='highest_price_since_entry',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_trailing_sl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='lowest_price_since_entry',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sl_trail_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='stop_loss_type',
            field=models.CharField(blank=True, choices=[('POINT', 'Point Wise'), ('PRICE', 'Price Wise'), ('PNL', 'P&L Wise')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='stop_loss_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='target_type',
            field=models.CharField(blank=True, choices=[('POINT', 'Point Wise'), ('PRICE', 'Price Wise'), ('PNL', 'P&L Wise')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
