# Generated by Django 6.1.1 on 2026-09-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_portfolio_highest_pnl_since_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_trading_halted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='margin_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wallet',
            name='max_open_positions',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='wallet',
            name='short_margin_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
    ]
