# Generated by Django 6.1.1 on 2026-09-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_type',
            field=models.CharField(choices=[('INTRADAY', 'Intraday'), ('NORMAL', 'Normal (Delivery)')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='reference_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='slippage_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='validity',
            field=models.CharField(choices=[('DAY', 'Day'), ('IOC', 'IOC'), ('GTT', 'GTT'), ('AMO', 'AMO - After Market')], default='DAY', max_length=10),
        ),
    ]
