# Generated by Django 6.1.1 on 2026-09-18 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_order_product_type_order_reference_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Basket', max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('target_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stop_loss_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_trailing_sl', models.BooleanField(default=False)),
                ('trailing_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('highest_pnl_since_entry', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('allocated_fund', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fund_used', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.PositiveIntegerField()),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trading.basket')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.stock')),
            ],
        ),
        migrations.CreateModel(
            name='BasketAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_fund', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fund_used', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='trading.basket')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.stock')),
            ],
            options={
                'unique_together': {('basket', 'stock')},
            },
        ),
    ]
