# Generated by Django 6.1.1 on 2026-09-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_basket_basketitem_basketallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='validity',
            field=models.CharField(choices=[('DAY', 'Day'), ('IOC', 'IOC'), ('GTT', 'GTT'), ('AMO', 'AMO - After Market'), ('SCHEDULED', 'Scheduled')], default='DAY', max_length=10),
        ),
    ]
